name: pcyb
description: pcyb

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  equatable: ^2.0.3
  firebase_auth: ^3.11.2
  firebase_core_platform_interface:
  firebase_core: ^1.17.0
  firebase_database: ^9.0.14
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_dotenv: ^5.0.2
  flutter_form_builder: ^7.0.0
  flutter_hooks: ^0.18.1
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.0.8
  form_builder_validators: ^8.3.0
  freezed_annotation: ^2.1.0
  go_router: ^4.5.1
  json_annotation: ^4.4.0
  loading_indicator: ^3.0.2
  provider: ^6.0.2
  shimmer_animation: ^2.1.0+1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_gen_runner: ^5.0.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  go_router_builder: ^1.0.3
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true

  # assets:
  #   - lib/assets

flutter_intl:
  enabled: true

dependency_overrides:
  intl: 0.17.0

flutter_gen:
  integrations:
    flutter_svg: true